name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg-cache
  VCPKG_ROOT: C:\vcpkg

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: ./.github/actions/ci
      with:
        cmake-preset: vs2022-windows
        artifact-name: StaffEnchanting

  build-vr:
    runs-on: windows-latest

    steps:
    - uses: ./.github/actions/ci
      with:
        cmake-preset: vs2022-windows-vr
        artifact-name: StaffEnchanting-VR
