name: Scripted maintenance

on: push

jobs:
  maintenance:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Run clang-format
      run: find -type f \( -name *.h -o -name *.hpp -o -name *.inl -o -name *.cpp \) | xargs clang-format-18 -style=file -i

    - uses: stefanzweifel/git-auto-commit-action@v5.0.1
      with:
        commit_message: maintenance
